### ISSUE TITLE
Peer to Peer Code Review.

### ISSUE THREAD

**Issue by Ogaga01** [JauJau088/leaderboard-with-api#3]
## Hello Jau.

<img src="https://media2.giphy.com/media/kGXcQp3dWrU44hfnqq/giphy.gif"/>

Great job on completing the project and implementing all the requirements.
We have found no Issues with this code. Code is clean 👍 

## Highlights:
- [x] Great use of Gitflow
- [x] Great use of semantic HTML
- [x] Your code is DRY
- [x] API is properly used.

Have a great day Jau 👋 
Cheers 🍷 and Happy coding 💻

**Comment by JauJau088** [comment]
Thanks guys for the review.

I am closing the thread now.

Cheers 🥂
